### ISSUE TITLE
Repository source code contains Redis distribution

### ISSUE THREAD

**Issue by dskecse** [SmolinPavel/hello-world#1]
## What's Up

Currently, the repo's source code contains Redis distribution, which, to put it mildly, is not considered a good practice. Instead, you should have installed Redis locally (idk, maybe you already have) via, say, Homebrew:

    brew install redis

and should not have committed it to the repo.

/cc @SmolinPavel

**Comment by SmolinPavel** [comment]
Gotcha, thanks!
I guess I could just use .gitignore to make it nice?

**Comment by dskecse** [comment]
I'd recommend to only add `node_modules` to `.gitignore`. As for `redis-stable` dir and the archive, remove them and commit the changes.

**Comment by SmolinPavel** [comment]
Copy that
